# Site settings
title: andrew stroup
sub_title: made in korea, raised in cowboy boots
email: stroupaloop@gmail.com
description: The personal landing page and blog of Andrew Stroup
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://stroupaloop.com" # the base hostname & protocol for your site
twitter_username: stroupaloop
github_username: stroupaloop

# Build settings
markdown: kramdown

exclude:
  - s3_website.yml
  - README.md
  - Gemfile
  - Gemfile.lock